### ISSUE TITLE
Not working when i make nova_defender or !nova

### ISSUE THREAD

**Issue by darkaloibou** [Freilichtbuehne/nova-defender#7]
I'm on the gamemode Begotten III, when i try to make the command. It is not working. I also try with the command. nova add "STEAM_0:1:12345678" "superadmin" "Person's name", but it is not fixing the issue that the client has not the pannel. 
I also check and it load at the start.

**Comment by Freilichtbuehne** [comment]
Hello, can you please send the exact command (you can replace the SteamID) you executed?

- What is the output of the command?
- Are other commands like `nova help` working?
- Can you add the SteamID within the menu of nova to the protected users?
- Does Nova throw any errors in the server console when you restart it?

**Comment by darkaloibou** [comment]
Hi, here are the tests :

- command made in the console : _nova_defender_ and _say !nova_
error : Unknown command: nova_defender

- nova help or nova is working. It sends the help in the console server.

- Command to add someone in the white list : nova list
["STEAM_0:1:12345678"]:
["comment"] = Person's name
["group"] = superadmin
["steamid"] = STEAM_0:1:12345678

command : _nova add "STEAM_0:1:12345678" "superadmin" "Person's name"_

- The menu is not opening. I try but no way.

- Nova don't send any error

**Comment by Freilichtbuehne** [comment]
We resolved the error by replacing `STEAM_0:1:12345678` with his actual SteamID.
